name: Update README on Push

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here if needed

    - name: Run Python script to update README
      run: python updateReadme.py

    - name: Commit and push if changes
      run: |
        git config user.name 'ziebamikolaj'
        git config user.email 'ziebamikolaj03@gmail.com'
        git add *
        git diff --staged --quiet || (git commit -m "Update README with Python script changes"; git push https://${GH_PAT}@github.com/ziebamikolaj/advent-of-code-2023.git)
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
