name: Update README on Push

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here if needed

    - name: Run Python script to update README
      run: python updateReadme.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'ziebamikolaj'
        git config --global user.email 'ziebamikolaj03@gmail.com'
        git add README.md
        git commit -m "Update README with progress"
        git push
